apiVersion: v1
kind: Service
metadata:
    name: frontend-node-port
spec:
    type: NodePort
    ports:
        - port: 3050
          targetPort: 3000
          nodePort: 32121
    selector:
        component: frontend